        success, img = cap.read()
        img = cv2.imread('blackC.jpg')
        img = cv2.flip(img, 0)
        img = cv2.flip(img, 1)
        # img = crop(img)
        imgContour = img.copy()
        threshold1 = cv2.getTrackbarPos("Threshold1", "Parameters")
        threshold2 = cv2.getTrackbarPos("Threshold2", "Parameters")
        hsv_img = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
        # lower_black = np.array([0, 0, 0])
        # upper_black = np.array([35, 55, 100])
        colorMask = cv2.inRange(hsv_img, lower, upper)
        getContours(colorMask, imgContour)
        cv2.imshow("Result", imgContour)
        cv2.setMouseCallback('Result', mouseClickHandler)
        getImageCoordinates()
